### ISSUE TITLE
Command line example for import-export failing to set partition name

### ISSUE THREAD

**Issue by wilke** [ExaWorks/psi-j-python#161]
Executing `python scripts/import-export.py` creates following error:

Traceback (most recent call last):
File "scripts/import-export.py", line 36, in 
jex.submit(job)
File "/home/wilke/miniconda3/envs/psi-j-py3.7/lib/python3.7/site-packages/psi_j_python-0.1-py3.7.egg/psij/executors/batch/batch_scheduler_executor.py", line 195, in submit
raise SubmitException(ex.output) from None
psij.exceptions.SubmitException: sbatch: error: invalid partition specified: None
sbatch: error: Batch job submission failed: Invalid partition name specified

**Comment by wilke** [comment]
Added test for none value to export.
