### ISSUE TITLE
Executors missing `__VERSION__`

### ISSUE THREAD

**Issue by SteVwonder** [ExaWorks/psi-j-python#41]
```
❯ python3 -c 'from psi.j.job_executor import JobExecutor; exec = JobExecutor.get_instance("local"); print(exec.version)'                                                                                   19:35:22 ()
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/herbein1/Repositories/exaworks/psi-j-python/.virtualenv/lib/python3.9/site-packages/psi/j/job_executor.py", line 69, in version
    return cast(Version, getattr(self.__class__, '__VERSION__'))
AttributeError: type object 'LocalJobExecutor' has no attribute '__VERSION__'
```

**Comment by hategan** [comment]
The classes have `_VERSION_` (with single underscores), which is what is used everywhere else, so line 69 should be changed accordingly.
